### ISSUE TITLE
Travis build breaking (looks like a Travis + IPv6 issue)

### ISSUE THREAD

**Issue by ptaoussanis** [http-kit/http-kit#260]
Link: https://travis-ci.org/http-kit/http-kit/builds/111940206

This is the test:
```clojure
(deftest test-ipv6
  ;; TODO add more
  (is (= "hello world" (:body (http/get "http://[::1]:4347/")))))
```

Looks like it may be related to https://github.com/travis-ci/travis-ci/issues/4964. Just busy juggling a few things at work, will try take a proper look at this later.

**Comment by venantius** [comment]
That is really not the most helpful reply from them :stuck_out_tongue: 

If push comes to shove we can investigate other testing platforms as well and see if there's one out there that works. They basically all offer free tests for OSS projects.

**Comment by venantius** [comment]
After looking into this a bit more, it seems that basically any CI service running on AWS won't have IPv6 support (astonishingly enough). 

I would propose setting some test selectors that exclude the relevant IPv6 tests - we can then configure CI to run everything else, and be diligent manually around anything that touches IPv6 logic otherwise. 

I can probably make a PR for this.

**Comment by ptaoussanis** [comment]
Saw you'd self-assigned this but had a minute so just handled it quickly. Tests are still failing due to a recent commit, will investigate tonight.
