### ISSUE TITLE
Make the org.httpkit.client.HttpClient class non-final

### ISSUE THREAD

**Issue by kumarshantanu** [http-kit/http-kit#272]
I had to recently instrument this class for performance troubleshooting. Because this class is declared `final`, I could not just extend the class and put instrumentation wrapper over the areas of code I was inspecting. I had to copy the file as another class in order to put my instrumentation.

Please consider making this class non-final, i.e. omit the `final` modifier.

**Comment by kumarshantanu** [comment]
I would be happy to submit a pull request if the idea sounds reasonable.

**Comment by mhjort** [comment]
I don't see any reason why not. I think protecting this class from overriding is a bit overkill. @venantius, @ptaoussanis what do you think?

May I ask what are your requirements for instrumenting the class? Could access to thread pool (or possibility to give your own one) as suggested here #231 help instead?

**Comment by kumarshantanu** [comment]
In my case I found out an increased latency during hostname lookup (for a particular remote host):
https://github.com/http-kit/http-kit/blob/master/src/java/org/httpkit/client/HttpClient.java#L237

I build some throwaway harness for instrumenting portions of code. When the portions are inside a method, I copy the current source code of the method and put instrumentation around the portions of interest. So, essentially my requirement is only that the classes and methods not be `final` as much as possible. :)

**Comment by mhjort** [comment]
Hear you. Please go ahead with PR.

Btw, I'm using httpkit client in my load testing tool and have found similar issues related to network address translation under heavy load. I don't know if you're facing the same latency problem but in my case this call helped:

` (java.security.Security/setProperty "networkaddress.cache.ttl" "-1"))`

This will set JVM network address cache to never refresh. In load testing this was the thing I wanted since cache refresh sometimes blocks under heavy load.

**Comment by kumarshantanu** [comment]
@mhjort Thanks for the tip, I may use it sometime. In my case it eventually appeared to be a transient name server issue.

I have sent in #273 as a PR to this issue.
