### ISSUE TITLE
Connection limit client 

### ISSUE THREAD

**Issue by royalaid** [http-kit/http-kit#282]
I was wondering if there is a way to limit the number of active connections a client will make and maintain. So if I want to limit to 20 connections the client will wait to issue requests after 20 unanswered callbacks are in queue.

**Comment by hamidr** [comment]
I guess it's not httpkit's business... I also want this feature but I think it's better to get handled somewhere else.

**Comment by ptaoussanis** [comment]
Related to #293 

Any reason you wouldn't want to just rate limit Clojure-side or with a Java semaphore?

**Comment by royalaid** [comment]
I can't see any reason why it couldn't be done at a higher level, that is what I did just using an atom, but adding it directly greatly would ease the implementation.

**Comment by ptaoussanis** [comment]
Okay, thanks for the confirmation. Am keen to keep http-kit's core as small as possible for the moment, esp. since the primary maintainer isn't involved right now.

Since Java+Clojure already both have pretty good tools for general rate limiting, going to close this for now as low priority. May reevaluate again later if there's consistent demand.

Appreciate you bringing this up. Cheers! :-)
