### ISSUE TITLE
Server feature request: Add support for request measurements?!

### ISSUE THREAD

**Issue by kaibra** [http-kit/http-kit#308]
Hey,

we use http-kit for some of our microservices. For us it is very important to have an overview of our response times: How long does it take to handle a request and return the response?
Up to now we were measuring things inside our clojure-handlers.

I had the idea to do the measurements inside http-kit close to the SocketChannels.
This would have 2 main advantages:

- out of the box measurements for all clj-routes
- more accurate measurements (since closer to the sockets)

What do you think of such an idea?
I would add a pull-request with an implementation, if you think this could be part of http-kit.
But if so, some questions need to be clarified before:

e.g. How would timings be reported/stored/provided?
My current implementation of this uses a IFn you can pass to the HttpServer, which is called every time, a request is finished. As parameters, it passes to the IFn the IPersistentMap from the RingHandler and the measured time.
It has the risk, that the IFn (if not async) slows down the server but on the other hand gives you complete freedom (log timings, report them to a server, ...).
Maybe a better solution would be, to have sth like a dropping-buffer which can be accessed from outside?!

How could the measurement be implemented?
I thought of using the ServerAtta to store the measurement info, since it is attached to the SelectionKey.

Let me know what you think...

Regards,

Kai

**Comment by ptaoussanis** [comment]
Hi there,

Thanks for the clear info, and for checking in before starting work on a PR! Appreciate it :-)

My general preference is to try and keep http-kit's codebase as small and simple as possible, especially since the project currently doesn't have any dedicated developers.

It seems to me that these kinds of performance measurements could be quite reasonably (better?) handled by some combination of:

1. Standard benchmarking tools like [wrk2](https://github.com/giltene/wrk2), etc.
2. App-level profiling tools like [tufte](https://github.com/ptaoussanis/tufte).

In particular, it shouldn't be too difficult to write some Ring middleware to profile the routes that you're interested in, etc.

And this way we get to keep from adding additional code to http-kit.

Does that make sense / seem reasonable?

Cheers :-)

**Comment by kaibra** [comment]
Sure, no problem :)
I didn't know about tufte. It looks quite interesting.
