### ISSUE TITLE
Can't make a simple GET on upvote.pub

### ISSUE THREAD

**Issue by achikin** [http-kit/http-kit#368]
A simple `get` to `https://upvote.pub` fails with an error
```clojure
=> @(http/get "https://upvote.pub")
{:opts {:method :get, :url "https://upvote.pub"}, :error #error {
 :cause "No status"
 :via
 [{:type org.httpkit.ProtocolException
   :message "No status"
   :at [org.httpkit.client.RespListener onCompleted "RespListener.java" 126]}]
 :trace
 [[org.httpkit.client.RespListener onCompleted "RespListener.java" 126]
  [org.httpkit.client.Request finish "Request.java" 51]
  [org.httpkit.client.HttpClient doRead "HttpClient.java" 156]
  [org.httpkit.client.HttpClient run "HttpClient.java" 426]
  [java.lang.Thread run "Thread.java" 745]]}}
```

**Comment by jiacai2050** [comment]
Maybe the same with https://github.com/http-kit/http-kit/issues/367

**Comment by owengalenjones** [comment]
I'm seeing this issue too, for a different URL.  On some machines it is a successful request, but in production it throws the "No status" exception.

Trying to the `2.3.0-alpha5` branch with Java 8 tomorrow, will report my results.

**Comment by owengalenjones** [comment]
@achikin so I was able to replicate your issue (albeit with a different URL) and fixed it by switching httpkit to `2.3.0-alpha5` and to Java 8.

**Comment by ptaoussanis** [comment]
Thanks for the suggestions @jiacai2050, @owengalenjones 👍

@achikin Can this be closed?

**Comment by miikka** [comment]
In case of https://upvote.pub, it seems that nowadays connecting fails during the SSL handshake. You can't connect to it with cURL or a browser, either. Probably the service has been removed from Google App Engine but the domain still points there, or something like that. Whatever the issue was in 2018, I don't think it can be reproduced anymore.

Throwing a ProtocolException seems sensible to me even if the error message is a bit opaque.

**Comment by ptaoussanis** [comment]
Closing as part of issue triage due to inactivity.
Please feel free to re-open if this issue is still relevant.
