### ISSUE TITLE
Is this repo being maintained?

### ISSUE THREAD

**Issue by ethpran** [http-kit/http-kit#416]
Hi,

I just want to check on the status here. I'd be happy to help with some of the open issues but I'd just like to be sure my PRs will get attention if I submit. I submitted one a while ago and it never got any feedback. I see others which have been submitted as well.

**Comment by ptaoussanis** [comment]
Hi @ethpran, repo is being maintained on a best-effort basis.

PRs are welcome once the `pull-requests welcome` label has been assigned to an issue.
The most common causes of having a PR unmerged are:

  - PRs addressing a feature or problem that isn't sufficiently clearly described/motivated.
  - PRs that are overly broad, unnecessarily breaking, or with tradeoffs that haven't been clearly described.
  - Triage / limited reviewer time: attention will normally be prioritised for issues with a wide or significant user impact.

Well-documented, high-quality PRs are the likeliest to get merge since they're practically the easiest/quickest to review.

Hope that makes sense!

I did a quick check on PRs and couldn't find one with your username. Feel free to ping if you can point me in the right direction and I'll try take a look at it :-)
