### ISSUE TITLE
Expired http-kit.org domain

### ISSUE THREAD

**Issue by tzzh** [http-kit/http-kit#424]
The http-kit.org domain expired and the docs site is therefore no longer available.

**Comment by j-pb** [comment]
I'd be more than happy to donate a few bucks to keep it running 💸

**Comment by gerritjvv** [comment]
I'd be happy to pay for the domain/hosting to keep this up and running. Send me an email to gerritjvv@gmail.com

**Comment by didiercrunch** [comment]
I can give too.

**Comment by ptaoussanis** [comment]
Hi everyone, thanks for the offers to help support the domain!

I've tweaked the GitHub pages config to restore access to site content via http://http-kit.github.com/. More info at https://github.com/http-kit/http-kit.github.com/commit/4c3dce0b8c2f680f9e85b08420732e6e70671c1b. (Note that it may take some time for DNS to update).

I think it might be easier long-term if we just make that the canonical URL for http-kit, instead of maintaining a separate .org domain?

Thanks again!
