### ISSUE TITLE
Update old Netty dep (used for unit tests)

### ISSUE THREAD

**Issue by asilverman** [http-kit/http-kit#431]
Please update io.netty_netty-codec as since [critical CVE-2019-16869](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2019-16869) is impacting versions <4.1.42

Current project is using version "3.6.5.Final"

**Comment by ptaoussanis** [comment]
Hi Ariel, thanks a lot for pinging about this!

It shouldn't be a security concern since http-kit doesn't actually use Netty in production.
Netty is only a dependency for the unit tests.

It would be nice to update the dependency anyway, but there's breaking changes involved- so this would need a community PR.

**Comment by caioguedes** [comment]
Hey @ptaoussanis, just opened a PR for this issue. Let me know, if more changes are needed. :smile:
