### ISSUE TITLE
Consecutive encoded forward slashes are removed from requests :uri

### ISSUE THREAD

**Issue by frerom** [http-kit/http-kit#450]
If I call the server with the URI `localhost/one//two` I get `localhost/one/two` when calling `(:uri request)` in my handler. It has come to my attention that this might be expected behavior, however the same thing happens when calling `localhost/one/%2Ftwo` where `%2F` is a URI encoded forward slash.

Tested on version 2.5.0

**Comment by ptaoussanis** [comment]
@frerom Hi there. I'm sorry, could you please clarify: is this a question, or are you advocating for some change?
If advocating for a change, please provide more info so that reviewers can properly respond - for example:

- What exactly is the problem? (Including implications / consequences)
- What exactly is the proposal? (E.g. document something, change something, etc.)

Thanks!

**Comment by ptaoussanis** [comment]
Closing as part of issue triage due to inactivity.
Please feel free to re-open if this issue is still relevant.
