### ISSUE TITLE
java.lang.NoSuchMethodError introduced in 2.5.2

### ISSUE THREAD

**Issue by kumarshantanu** [http-kit/http-kit#462]
I started getting the following error with version `2.5.2` (doesn't happen with `2.5.1`, `2.5.0` etc.) when running the server:

```
Sun Feb 21 03:24:04 IST 2021 [server-loop] ERROR - http server loop error, should not happen
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at org.httpkit.server.HttpServer.doRead(HttpServer.java:249)
	at org.httpkit.server.HttpServer.run(HttpServer.java:378)
	at java.lang.Thread.run(Thread.java:748)
```

In my use-case I dynamically load the HTTP-Kit server namespace at runtime using `require`. I'm using Java 8 on Mac OS X Catalina.

**Comment by borkdude** [comment]
Can you post an isolated repro maybe?

**Comment by borkdude** [comment]
@kumarshantanu @ptaoussanis Maybe the 2.5.2 was built using Java 11 instead of 8?

Also see:

https://github.com/lmdbjava/lmdbjava/issues/116

**Comment by kumarshantanu** [comment]
I'm facing this error only when running Java 8. It works fine with Java 11 or higher.

**Comment by ptaoussanis** [comment]
@kumarshantanu Hi Shantanu, apologies for the trouble.

Could you please try with `[http-kit "2.5.3-SNAPSHOT"]` and let me know if that's better? (This is explicitly compiled with Java 8).

Issue looks related to https://github.com/http-kit/http-kit/issues/437, but I'm not certain off hand why the issue would have returned since the apparent [fix](https://github.com/http-kit/http-kit/blob/master/project.clj#L25).

If you can confirm that the snapshot works, I'll try take a closer look and in the meantime take Michiel's suggestion of automating the build with Java 8. (Thanks @borkdude!).

**Comment by ptaoussanis** [comment]
Quick update:

@kumarshantanu Actually if possible, would you please try both of these instead?:

- `[http-kit.debug "2.5.3-release7"]` ; Compiled with Java 11 using `--release 7 -g`
- `[http-kit.debug "2.5.3-jdk8"]` ; Compiled with Java 8 using `-source 1.7 -target 1.7 -g`

My hope + expectation is that both of them should now work.

**Comment by kumarshantanu** [comment]
@ptaoussanis All of `[http-kit "2.5.3-SNAPSHOT"]`, `[http-kit.debug "2.5.3-release7"]` and `[http-kit.debug "2.5.3-jdk8"]` are working fine. Thanks for the quick turnaround!

**Comment by ptaoussanis** [comment]
@kumarshantanu No problem, thanks a lot for the quick response!

`[http-kit "2.5.3"]` is now on Clojars with the fix 👍

**Comment by borkdude** [comment]
TIL: 

```
--release <release>
        Compile for a specific VM version. Supported targets: 6, 7, 8, 9, 10, 11
``` 

Thanks! I always did this by setting my JAVA_HOME to another JVM, but this is way easier.
