### ISSUE TITLE
Infinite / no timeouts

### ISSUE THREAD

**Issue by cap10morgan** [http-kit/http-kit#488]
Is it possible to configure the client to never timeout a request? My use case is I'm implementing the AWS Lambda runtime in babashka and the way that works is you open a GET request to receive the event payload representing the next invocation of your lambda handler fn, so it just blocks until a request comes in. The Lambda docs say not to timeout that request so that it can just wait for the next invocation. It's not a huge deal because you can just put it in a loop and loop back around when the timeout occurs. But it made me curious if an infinite / no timeout were possible / desirable in http-kit?

**Comment by ptaoussanis** [comment]
@cap10morgan Hi Wes. Doesn't appear to be possible from a quick look at the code. In any case, I think it'd probably be better to use a loop anyway since otherwise you'd run the possibility of a request being held for ages - in which case I expect you'd be more likely to run into possible issues with the TCP connection, proxies, etc.

**Comment by cap10morgan** [comment]
@ptaoussanis Makes sense. We can close this issue if you want.
