### ISSUE TITLE
Basic Project Template (Skeleton)

### ISSUE THREAD

**Issue by rawoke083** [http-kit/http-kit#492]
Hi Guys
http-kit looks really good ! But after spending the whole day trying to get THE BASICS up and running I had to move on and look somewhere else:

a bare-min-basic-example or template would go a long way

1) Basic hello world template (with latest http-kit) all examples online are years out of date
2) Basic examples + setup how to interact with project: Example: start, stop, debug, repl.

Is there no up to date project-skeleton somewhere??

**Comment by borkdude** [comment]
Perhaps this helps a bit:

It's an example of how to use http-kit server in babashka.

https://github.com/prestancedesign/babashka-htmx-todoapp

**Comment by rawoke083** [comment]
> Perhaps this helps a bit:
> 
> It's an example of how to use http-kit server in babashka.
> 
> https://github.com/prestancedesign/babashka-htmx-todoapp

No sorry. I thank you for providing the example but it does not address any of the issues.

a) a project-skeleton with LATEST and UPDATED documentation
b) With all the correct name-space requirements and versions
c) 2 routes ? Hello-world and websockets
d) propper project.clj or deps file
e) run, repl examples.

All of the documentation has these "little snippets" of code with no filenames. Good luck trying to figure that out if you new to clojure.

It has all these claims about performance and how simple it is. It definitely is not. Most of the snippets doesn't even work !

Maybe try taking a look at pedestal. At least they got working end-to-end examples.

*snippets of random code* without filenames, context or lack of actually being correct it useless.

**Comment by ptaoussanis** [comment]
@borkdude Thanks for the suggestion Michiel 👍

@rawoke083 Hi Jacques, unfortunately I'm not currently aware of any project template that fits your description.

PRs are welcome to improve any aspect of the documentation, otherwise closing this as part of issue triage.

As an aside, please note that http-kit is maintained by its community, and support is offered on a good faith basis by people donating their time to try to help. I'd encourage you to consider the effect that the phrasing of the [above response](https://github.com/http-kit/http-kit/issues/492#issuecomment-1177888332) may have on the motivation of contributors, and whether there might not be more effective ways to solicit assistance or give feedback.

Thanks
