### ISSUE TITLE
Handle closing connection by client

### ISSUE THREAD

**Issue by vganshin** [http-kit/http-kit#527]
Hello. I noticed that, when I call long polling request and then refresh the page, Chrome cancel the long polling request. But I don't see, how httpkit handles this.

For synchronous handler I expected to catch some exception:
```clojure
(defn handler [_req]
  (try
    {:status 200
     :body (deref @broadcaster 60000 "skip")}
    (catch Exception e
      (println e)
      {:status 200
       :body "connection closed by client"})))
```

Then I rewrote it in async format: 

```clojure
(def channels (atom #{})

(defn handler [req]
  {:response
   (org.httpkit.server/as-channel
    req
    {:on-open (fn [ch] (swap! channels conj ch))
     :on-close (fn [ch status]
                 (println "on close" status)
                 (swap! channels disj ch))})})
```

It helped me to at least release http workers. But it leads to increasing closed connections in channel atom.

I believe, that it is possible to detect closed TCP connection. So I wonder if there is an option to detect closed channels within httpkit?

**Comment by ptaoussanis** [comment]
@vganshin Hi Vladislav,

> I believe, that it is possible to detect closed TCP connection.

That is correct, but unfortunately browsers don't typically close TCP connections when refreshing a page (or following links, etc.). The underlying TCP connection is usually reused in these cases.

If the browser _does_ explicitly close the connection (for example if the page includes "Cache-Control: no-store" or "Pragma: no-cache", etc.) then the http-kit `:on-close` event handler will fire as expected.

Otherwise you'll need to implement your own logic for detecting these kinds of discarded connections.

That's quite a large topic, but you can see [Sente](https://github.com/ptaoussanis/sente)'s implementation if you're looking for some possible ideas - [here](https://github.com/ptaoussanis/sente/blob/5feac776c5ad73059b08df4b69bab3a6c5d97f7f/src/taoensso/sente.cljc#L814), for example.

I hope that helps?

**Comment by vganshin** [comment]
I got you. I knew (and successfully forgot), that browsers keep TCP connections alive. But I didn't thought that it reflects on server side in such a way.

Cache-Control, Pragma and even Connection: close headers didn't help. Anyway, async format it's not an issue anymore as it's needed in development. I just wanted to cleanup resources.

Thank you.
