### ISSUE TITLE
NoSuchMethodError on projects AOT'd on java 21 but run on earlier java versions

### ISSUE THREAD

**Issue by rafd** [http-kit/http-kit#564]
If I build a project using http-kit 2.8.0-RC1, and AOT on Java 21, it fails to run on Java 17. 

(Continued [from conversation on Slack](https://clojurians.slack.com/archives/C01ALH5JGRJ/p1710986947613399))

I have made a [sample repo to reproduce the issue](https://github.com/rafd/http-kit-2.8-error-reproduce). 

To reproduce:
 - switch to java 21
 - `lein uberjar`
 - switch to java 17
 - for server, run `java -jar target/http-kit-uberjar-demo-0.0.1-standalone.jar server` 
 - for client, run `java -jar target/http-kit-uberjar-demo-0.0.1-standalone.jar client` 
 
Trying to start a server, I get:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'java.util.concurrent.ExecutorService java.util.concurrent.Executors.newVirtualThreadPerTaskExecutor()'
        at org.httpkit.utils$new_worker$fn__214.invoke(utils.clj:69)
        at org.httpkit.utils$new_worker.invokeStatic(utils.clj:77)
        at org.httpkit.utils$new_worker.invoke(utils.clj:46)
        at org.httpkit.server$new_worker.invokeStatic(server.clj:57)
        at org.httpkit.server$new_worker.invoke(server.clj:48)
        at org.httpkit.server$run_server.invokeStatic(server.clj:156)
        at org.httpkit.server$run_server.doInvoke(server.clj:73)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at app$_main.invokeStatic(app.clj:14)
        at app$_main.doInvoke(app.clj:7)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at app.main(Unknown Source)
```

Trying to issue a request with the client, I get:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'java.util.concurrent.ExecutorService java.util.concurrent.Executors.newVirtualThreadPerTaskExecutor()'
        at org.httpkit.utils$new_worker$fn__214.invoke(utils.clj:69)
        at org.httpkit.utils$new_worker.invokeStatic(utils.clj:77)
        at org.httpkit.utils$new_worker.invoke(utils.clj:46)
        at org.httpkit.client$new_worker.invokeStatic(client.clj:98)
        at org.httpkit.client$new_worker.invoke(client.clj:89)
        at org.httpkit.client$fn__547$fn__548.invoke(client.clj:113)
        at clojure.lang.Delay.deref(Delay.java:42)
        at clojure.core$deref.invokeStatic(core.clj:2337)
        at clojure.core$deref.invoke(core.clj:2323)
        at org.httpkit.client$request.invokeStatic(client.clj:338)
        at org.httpkit.client$request.doInvoke(client.clj:214)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at org.httpkit.client$get.invokeStatic(client.clj:368)
        at org.httpkit.client$get.doInvoke(client.clj:368)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at app$_main.invokeStatic(app.clj:12)
        at app$_main.doInvoke(app.clj:7)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at app.main(Unknown Source)
```

**Comment by ptaoussanis** [comment]
@rafd Hi Rafal, thanks for the reproducible example! 🙏

Michiel seems to be correct (thanks @borkdude!), I was under the mistaken impression that an uberjar would still be okay in this case.

I'm really sorry about the confusion! Will update the release notes to add a warning, and will make sure any future releases are similarly marked when necessary.

Thanks a lot for pinging about this! 👍

**Comment by ptaoussanis** [comment]
Release notes have been [updated](https://github.com/http-kit/http-kit/commit/38773219d4f8b273131709bc117f3c84e986e5af) 👍

**Comment by rafd** [comment]
Looking at the code, it seems http-kit _could_ check for this at runtime, with a `delay`-cached value (like it does with `java-version`) instead of baking it in with the `if-compile` macro. Is doing it the way it is motivated by performance?

Whatever the reason, I'm content with the release warning. Hopefully if someone else runs into this, they'll find this issue and spend less time confused. (I'm still angry at brew for auto-updating my java).

Thanks for your work on http-kit @ptaoussanis and @borkdude!

**Comment by borkdude** [comment]
> Is doing it the way it is motivated by performance?

I'd say both performance and graalvm native-image compatibility (you can't do the runtime check there anymore)

**Comment by ptaoussanis** [comment]
@rafd

> Looking at the code, it seems http-kit could check for this at runtime, with a delay-cached value (like it does with java-version) instead of baking it in with the if-compile macro

I'm not aware of any obvious/straight-forward way of doing this at runtime, but happy to see an example if you have something in mind.

The purpose of the [delay](https://github.com/http-kit/http-kit/blob/33bb329466d484978446137f5711704a6bb17b40/src/org/httpkit/utils.clj#L28) in `java-version>=` is just for performance- the function body could just as well be `(>= (java-version) (long n))`. What matters is that `java-version>=` is a function, so that it's checked at runtime.

That's something that can be checked at runtime easily enough, because the decisions we make based on the outcome don't influence code generation - just branching.

The case of virtual threads is a little different since it involves code generation. We essentially want something like `(defn get-thread [] <body>)` that returns a virtual thread when possible. It's this body that would contain the conditional compile. Without the conditional compile, it's not obvious to me how you'd access virtual threads when they're available.

May be missing something though.

**Comment by rafd** [comment]
Where is the code-generation? [This](https://github.com/http-kit/http-kit/blob/master/src/org/httpkit/utils.clj#L68) seems to be the only place where the Virtual Thread support check is made, and it could just be a run-time if:

https://github.com/http-kit/http-kit/compare/master...rafd:http-kit:runtime-virtual-thread-check

Sorry if I am misunderstanding.

**Comment by rafd** [comment]
Ah, I missed borkdude's comment re: graalvm. If it must be compile-time for graal, then it makes sense.

**Comment by ptaoussanis** [comment]
> [This](https://github.com/http-kit/http-kit/blob/master/src/org/httpkit/utils.clj#L68) seems to be the only place where the Virtual Thread support check is made, and it could just be a run-time if

Have you tried this code on Java < 21?

`(fn [] (java.util.concurrent.Executors/newVirtualThreadPerTaskExecutor))` won't be allowed since that method won't exist.

> Sorry if I am misunderstanding.

No worries, it's good to check! I made one mistake on this myself already - extra eyes never hurt!

**Comment by rafd** [comment]
Gotcha. Facepalm. (I had installed my patched http-kit version on java 21 - which did work in a project on both 17 and 21, but not if http-kit was built on 17 and run in a project on 17).

So, I have another patch on offer (it's become more of an academic exercise at this point):

https://github.com/http-kit/http-kit/compare/master...rafd:http-kit:948738ea303c8bdae596ff7c7e6f1a1e83a77f43

It uses reflection. But the reflection is done in a way that [Graal is able to automatically detect](https://www.graalvm.org/22.0/reference-manual/native-image/Reflection/#automatic-detection) -- at least, I was able to use native-image on [my updated test repo](https://github.com/rafd/http-kit-2.8-error-reproduce) without any extra config or problems.

But it does leave the question of performance. The `getMethod` is cached, so it's a question of how much overhead the `invoke` adds after the JVM has warmed up. The JVM may be able to optimize it out completely for the same reason graal is happy with it. (For babashka, it would presumably have 0 penalty).

I've already been bit by the original issue and learned from it, so I don't have much of a horse in this race anymore -- so I'm totally fine with it being a wont-fix.

**Comment by ptaoussanis** [comment]
> So, I have another patch on offer (it's become more of an academic exercise at this point

I support the academic exercise, it's a useful case for some exploration 👍 Reflection would be the way to go if we really wanted to do this at runtime for some reason.

Note that performance doesn't actually matter much here since we're talking about code that runs only when creating a worker pool.

That'll usually only happen twice (once for client worker + once for server worker), certainly rarely - so reflection cost doesn't actually matter much. Likewise the delay wouldn't be too important so you could simplify to something like:

```clojure
(let [<...>
      new-virtual-pool
      (try
        (let [^java.lang.reflect.Method m
              (.getMethod java.util.concurrent.Executors
                "newVirtualThreadPerTaskExecutor" nil)]
          (fn [] (.invoke m nil nil)))
        (catch Throwable _ nil))]
  <...>)
```

I'm not familiar enough with GraalVM to say whether that'd cause any build problems without actually trying it - but I guess that should be fine. And performance shouldn't be an issue here either IMO, for the reason already discussed (this code runs rarely, usually just once). Even if one cares about the extra 1-time startup cost for something like Babashka, this reflection's in the order of < 0.5ms.

Anyway, that's on the academic end.

Re: whether to actually consider such a change or not - I wouldn't be keen to take on the extra complexity since I just don't think it'd buy us much. It's generally a good idea anyway to be in the habit of AOTing against the oldest Java release you want to support (see Sean Corfield's [comment](https://clojurians.slack.com/archives/C01ALH5JGRJ/p1710996989134989?thread_ts=1710986947.613399&cid=C01ALH5JGRJ) for one example why).

And there may be other areas in http-kit where we already do (or will in future want to do) similar compile-time conditionals. Then we'd be forced to adopt the same complexity in those areas too to retain the marginal benefit.

So my 2c- release notes should definitely bring attention to such changes when they're introduced, but I'm also happy that that should be sufficient - and simpler.

Hope that seems reasonable?

**Comment by ptaoussanis** [comment]
@rafd Okay with you to close this?

**Comment by rafd** [comment]
OK.
